# Generated by Django 4.1.4 on 2022-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filesend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Designation', models.CharField(max_length=50, null=True)),
                ('Files', models.FileField(upload_to='')),
                ('Department', models.CharField(choices=[('manager', 'manager'), ('employer', 'employer')], max_length=200, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('On-progress', 'On-progress'), ('Complete', 'Complete')], max_length=200, null=True)),
            ],
        ),
    ]
