# Generated by Django 4.1.4 on 2022-12-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tracker', '0002_filesend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='Is employer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teamleader',
            field=models.BooleanField(default=False, verbose_name='Is teamleader'),
        ),
    ]
